### ISSUE TITLE
Discord Invite Link expired

### ISSUE THREAD

**Issue by Xwilarg** [Kadantte/kadantte#1]
Hey,

Just opening an issue to tell you that the Discord link in your README doesn't work

**Comment by ariesclark** [comment]
this remains true, 8 days later.

**Comment by Xwilarg** [comment]
(And on a side note, this link on the README is also dead: https://github.com/Kadantte/Lida-Assistant )

**Comment by Kadantte** [comment]
> Hey,
> 
> Just opening an issue to tell you that the Discord link in your README doesn't work

sorry for the late reply since I'm on `Conscription`! anyway I updated the link to discord server also you can contact me from here too: `Jae Jin#0256`

**Comment by Kadantte** [comment]
> (And on a side note, this link on the README is also dead: https://github.com/Kadantte/Lida-Assistant )

for this one, It's still a private repo since I didn't have time to advance on it!
