### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by Xwilarg** [Kadantte/kadantte#2]
The following links in your README are leading to a 404
- https://github.com/Oppa-TECH/oppa.tech
- https://github.com/Kadantte/kadantte/blob/master/Usui#0256
- https://github.com/deeppomf/DeepCreamPy (For this one the [project was deleted](https://www.reddit.com/r/AnimeResearch/comments/mg2ro4/what_happened_to_deepcreampy/gss1eha?utm_source=share&utm_medium=web2x&context=3))

**Comment by Kadantte** [comment]
Fixed on 06f3dbe0e5286d334174fe2487a9597e524f5077 and 8da06a15e5cad1af019f31cfac4e7c4190405ccd !

For the private, It's a project for my company!

![image](https://user-images.githubusercontent.com/11579313/122934208-3d642e80-d367-11eb-9fee-653e260da976.png)

![image](https://user-images.githubusercontent.com/11579313/122934284-4d7c0e00-d367-11eb-863f-667e1602fd62.png)

**Comment by micwoj92** [comment]
I dont think that it makes sense to link to repo then, just link to company page.

**Comment by Kadantte** [comment]
Done! 6bc496bc488a426a02d2f19eb2ebdac233b51aa0
