### ISSUE TITLE
Contact doesn't work

### ISSUE THREAD

**Issue by aliyss** [Kadantte/kadantte#3]
Basically the e-mail to admin@ doesn't work from the website. But more importantly the link to discord is invalid.

**Comment by Kadantte** [comment]
> Basically the e-mail to admin@ doesn't work from the website. But more importantly the link to discord is invalid.

The e-mail from my website works just fine! for the Discord link It's been fixed!

![image](https://user-images.githubusercontent.com/11579313/129445960-14f5b319-ca41-4e23-8534-09bac88d810b.png)

**Comment by aliyss** [comment]
![Screenshot_2021-08-14-19-48-52-27.jpg](https://user-images.githubusercontent.com/33941859/129457370-a88eacaf-fd2b-48b4-9caa-ff7b79764e6a.jpg)

Thanks for the discord one. I'll check again about the mail stuff... Might be on my side.

**Comment by Kadantte** [comment]
> ![Screenshot_2021-08-14-19-48-52-27.jpg](https://user-images.githubusercontent.com/33941859/129457370-a88eacaf-fd2b-48b4-9caa-ff7b79764e6a.jpg)
> 
> Thanks for the discord one. I'll check again about the mail stuff... Might be on my side.

Oh I see now it looks like the problem is from my end! anyway, try to contact me over this e-mail `jae-jin@kadantte.moe` I'll change it on the website!
